@startuml

class Container #PaleVioletRed
class YardBlock #lightgreen
class ContainerStack #lightgreen
class ContainerSlot #lightgreen
class YardCrane #LightCyan
class InternalTransferVehicle #LightCyan
class QuayCrane #LightCyan
class EquipmentControl #yellow
class GOS #GreenYellow
class Rail #beige
class RailCrane #beige
class Vessel #SkyBlue
class Berth #SkyBlue
class ContainerTerminal
class TOS #MediumOrchid
class YardPlanning #OrangeRed
class Gate #SeaGreen

ContainerTerminal --|> Gate
ContainerTerminal --|> Rail
ContainerTerminal --|> YardBlock
ContainerTerminal --|> Berth
'ContainerTerminal <..> TOS
'ContainerTerminal --|> YardCrane
'ContainerTerminal --|> InternalTransferVehicle
'ContainerTerminal --|> QuayCrane
'ContainerTerminal --|> Vessel

Gate <|-- GOS

Rail --> RailCrane

YardBlock --|> ContainerStack
ContainerStack --|> ContainerSlot
YardBlock --> YardCrane

'InternalTransferVehicle .. QuayCrane
'InternalTransferVehicle .. YardCrane
'InternalTransferVehicle .. RailCrane

Berth --> Vessel
Berth --> QuayCrane
Vessel --> QuayCrane

'Container .. Vessel
'Container .. YardBlock
'Container .. GOS

TOS <--> EquipmentControl
TOS --|> YardPlanning
TOS <--> GOS

YardPlanning <--> YardBlock

EquipmentControl <--> QuayCrane
EquipmentControl <--> YardCrane
EquipmentControl <--> InternalTransferVehicle
EquipmentControl <--> RailCrane
'EquipmentControl <--> GOS
'EquipmentControl <--> YardBlock

@enduml
