@startuml

class ContainerTerminal {
    -number_of_berths: int
    -number_of_quay_cranes: int
    -number_of_yard_blocks: int
    -number_of_yard_cranes: int
    -yard_crane_type: string
    -number_of_rail_tracks: int
    -rail_includes_buffer_storage_block: boolean
    -number_of_rail_cranes: int
    -rail_crane_type: string
    -number_of_itv: int
    -itv_type: string
    -number_of_entrance_gates: int
    -number_of_exit_gates: int
}

@enduml