@startuml

class ContainerSlot {
    -block_id : string
    -slot_tier_id : string
    -is_ground : boolean
    -is_top_tier : boolean
    -slot_status : string
    -container_id : string
    -cycle_id : string
    -upper_neighbor_slot_status : list

    +update_slot_info()
    +update_neighbor_slot_status()
}

@enduml