@startuml
class Container {
    -id: String
    -size: Integer
    -type: String << see container_type.json >>
    -cargo_type: String << see cargo_type.json >>
    -iso_code: String
    -cycle_id: String
    -transit_state: String
    -time_in: DateTime
    -time_out: DateTime
    -facility: String
    -weight: Float
    -category: String
    -freight_kind: String
    -line_operator: String
}
@enduml
