@startuml

class QuayCrane {
    - crane_id: string
    - crane_icon_id: string
    - crane_type: string
    - crane_status: string
    - login_id: string
    - twin_lift_capable: boolean
    - active_work_queue: List<wi>
    - planned_work_queue: List<wi>
    - equipment_pool_id: string

    + fetch_container()
    + put_container()
}

@enduml