@startuml Rail

class Rail {
    -number_of_tracks: int
    -temporary_storage_supported: boolean
    -assigned_work_instructions: List<String>
    -equipment_pool_id: String

    +rail_transfer_wagon_itv(): void
    +rail_transfer_wagon_temporary_storage(): void
    +rail_fetch_put_yard_itv(): void
    +rail_carry_yard_transfer_point(): void
}

@enduml