@startuml
title Unload Container from Vessel by one QC
autonumber
' participant Participant as Foo
' actor       Actor       as Foo1
' boundary    Boundary    as Foo2
' control     Control     as Foo3
' entity      Entity      as Foo4
' database    Database    as Foo5
' collections Collections as Foo6
' queue       Queue       as Foo7
actor SimControl
entity Vessel as VS
entity QC
control CarryReadyAtQC
queue ITVs
entity ITV
control TOS
entity YBExchangeZone as YBEx
control CarryReadyAtYC
entity YC
entity YB
SimControl -> QC : Run simulation
loop Number of TC in QC Job List times
    ITV -> ITVs : ITV MOVE to QC zone
    VS -> QC : QC FETCH TC from vessel
    CarryReadyAtQC -> CarryReadyAtQC : ITV Carry Ready ?
    QC -> ITV : QC PUT TC to ITV
    ITV -> YBEx : ITV MOVE to YB exchange zone
    YBEx -> CarryReadyAtYC : ITV Put Ready ?
    YC -> CarryReadyAtYC : YC MOVE to YB exchange zone 
    CarryReadyAtYC -> YC : YC FETCH TC from ITV
    YC -> YB : YC PUT TC in YB
    YB -> QC : Next Job
end

@enduml