@startuml

class YardCrane {
    - id : string
    - icon_id : string
    - type : string << see yard_crane_type.json >>
    - max_weight : float
    - status : string << ex: active, inactive >>
    - login_id : string
    - twin_lift_capable : boolean
    - assigned_yard_zone : list
    - assigned_work_instructions : list
    - equipment_pool_id : string

    + fetch_container()
    + put_container()
}

@enduml